# Generated by Django 4.2.16 on 2024-11-03 16:38

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('key', models.CharField(default=users.models.generateKey, max_length=6, unique=True)),
                ('token', models.CharField(default=users.models.generateToken, max_length=60, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('level', models.CharField(max_length=50)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
