# Generated by Django 4.2.16 on 2024-11-04 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_sensorvalues_sensorpredicted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorpredicted',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor'),
        ),
    ]
