# Generated by Django 4.2.16 on 2024-11-04 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_sensorpredicted_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorpredicted',
            old_name='device',
            new_name='sensor',
        ),
    ]
